export interface CellTypeConfig {
    color: string;
    hardness: number;
    speedModifier: number;
    passThrough: boolean;
    isObstacle: boolean;
    isGround: boolean;
    damagedKey?: string;
    destroyedKey?: string;
}

export const CELL_TYPES = {
    ground: {
        color: '#2d2a1e',
        hardness: 0,
        speedModifier: 1.0,
        passThrough: true,
        isObstacle: false,
        isGround: true,
    },
    water: {
        color: '#3b82f6',
        hardness: 1,
        speedModifier: 0.4,
        passThrough: true,
        isObstacle: false,
        isGround: true,
    },
    forest: {
        color: '#166534',
        hardness: 1,
        speedModifier: 0.7,
        passThrough: true,
        isObstacle: false,
        isGround: true,
    },
    brick: {
        color: '#b45309',
        hardness: 2,
        speedModifier: 0.0,
        passThrough: false,
        isObstacle: true,
        isGround: false,
        damagedKey: 'brick_damaged',
        destroyedKey: 'brick_destroyed',
    },
    brick_damaged: {
        color: '#92400e',
        hardness: 1,
        speedModifier: 0.0,
        passThrough: false,
        isObstacle: true,
        isGround: false,
        destroyedKey: 'brick_destroyed',
    },
    brick_destroyed: {
        color: '#2d2a1e',
        hardness: 0,
        speedModifier: 0.7,
        passThrough: true,
        isObstacle: false,
        isGround: true,
    },
    concrete: {
        color: '#9ca3af',
        hardness: 3,
        speedModifier: 0.0,
        passThrough: false,
        isObstacle: true,
        isGround: false,
        damagedKey: 'concrete_damaged',
        destroyedKey: 'concrete_destroyed',
    },
    concrete_damaged: {
        color: '#6b7280',
        hardness: 1,
        speedModifier: 0.0,
        passThrough: false,
        isObstacle: true,
        isGround: false,
        destroyedKey: 'concrete_destroyed',
    },
    concrete_destroyed: {
        color: '#2d2a1e',
        hardness: 0,
        speedModifier: 0.7,
        passThrough: true,
        isObstacle: false,
        isGround: true,
    },
    steel: {
        color: '#9ca3af',
        hardness: -1,
        speedModifier: 0.0,
        passThrough: false,
        isObstacle: true,
        isGround: false,
    },
    reinforced: {
        color: '#1e40af',
        hardness: 8,
        speedModifier: 0.0,
        passThrough: false,
        isObstacle: true,
        isGround: false,
        damagedKey: 'reinforced_damaged',
        destroyedKey: 'reinforced_destroyed',
    },
    reinforced_damaged: {
        color: '#1e3a8a',
        hardness: 4,
        speedModifier: 0.0,
        passThrough: false,
        isObstacle: true,
        isGround: false,
        destroyedKey: 'reinforced_destroyed',
    },
    reinforced_destroyed: {
        color: '#2d2a1e',
        hardness: 0,
        speedModifier: 0.5,
        passThrough: true,
        isObstacle: false,
        isGround: true,
    },
    hardwall: {
        color: '#6b7280',
        hardness: 5,
        speedModifier: 0.0,
        passThrough: false,
        isObstacle: true,
        isGround: false,
        damagedKey: 'hardwall_damaged',
        destroyedKey: 'hardwall_destroyed',
    },
    hardwall_damaged: {
        color: '#4b5563',
        hardness: 2,
        speedModifier: 0.0,
        passThrough: false,
        isObstacle: true,
        isGround: false,
        destroyedKey: 'hardwall_destroyed',
    },
    hardwall_destroyed: {
        color: '#2d2a1e',
        hardness: 0,
        speedModifier: 0.5,
        passThrough: true,
        isObstacle: false,
        isGround: true,
    },
    metal: {
        color: '#d97706',
        hardness: 10,
        speedModifier: 0.0,
        passThrough: false,
        isObstacle: true,
        isGround: false,
        damagedKey: 'metal_damaged',
        destroyedKey: 'metal_destroyed',
    },
    metal_damaged: {
        color: '#92400e',
        hardness: 5,
        speedModifier: 0.0,
        passThrough: false,
        isObstacle: true,
        isGround: false,
        destroyedKey: 'metal_destroyed',
    },
    metal_destroyed: {
        color: '#2d2a1e',
        hardness: 0,
        speedModifier: 0.3,
        passThrough: true,
        isObstacle: false,
        isGround: true,
    },
    obsidian: {
        color: '#1e1b4b',
        hardness: 15,
        speedModifier: 0.0,
        passThrough: false,
        isObstacle: true,
        isGround: false,
        damagedKey: 'obsidian_damaged',
        destroyedKey: 'obsidian_destroyed',
    },
    obsidian_damaged: {
        color: '#0f0a3e',
        hardness: 7,
        speedModifier: 0.0,
        passThrough: false,
        isObstacle: true,
        isGround: false,
        destroyedKey: 'obsidian_destroyed',
    },
    obsidian_destroyed: {
        color: '#2d2a1e',
        hardness: 0,
        speedModifier: 0.3,
        passThrough: true,
        isObstacle: false,
        isGround: true,
    },
    base: {
        color: '#dc2626',
        hardness: 100,
        speedModifier: 0.0,
        passThrough: false,
        isObstacle: true,
        isGround: false,
    },
};

export type CellType = keyof typeof CELL_TYPES;

export function getCellConfig(type: CellType): CellTypeConfig {
    return CELL_TYPES[type];
}
