import { EnemyClass, EnemyConfig } from "./types";

export const ENEMY_CONFIGS: Record<EnemyClass, EnemyConfig> = {
    scout: {
        maxSpeed: 150,
        acceleration: 300,
        deceleration: 3,
        rotationSpeed: 200,
        size: 16,
        health: 30,
        color: '#f97316',
        darkColor: '#c2410c',
        bulletConfig: { speed: 350, size: 3, damage: 15 },
        shootCooldown: 1500,
        aggroRange: 400,
    },
    grunt: {
        maxSpeed: 70,
        acceleration: 250,
        deceleration: 3,
        rotationSpeed: 150,
        size: 28,
        health: 60,
        color: '#ef4444',
        darkColor: '#991b1b',
        bulletConfig: { speed: 280, size: 5, damage: 30 },
        shootCooldown: 2000,
        aggroRange: 350,
    },
    heavy: {
        maxSpeed: 40,
        acceleration: 200,
        deceleration: 2,
        rotationSpeed: 100,
        size: 36,
        health: 120,
        color: '#a855f7',
        darkColor: '#6b21a8',
        bulletConfig: { speed: 200, size: 8, damage: 60 },
        shootCooldown: 3000,
        aggroRange: 300,
    },
    artillery: {
        maxSpeed: 35,
        acceleration: 180,
        deceleration: 2,
        rotationSpeed: 80,
        size: 30,
        health: 50,
        color: '#eab308',
        darkColor: '#a16207',
        bulletConfig: { speed: 400, size: 6, damage: 45 },
        shootCooldown: 2500,
        aggroRange: 500,
    },
    commander: {
        maxSpeed: 55,
        acceleration: 220,
        deceleration: 2,
        rotationSpeed: 120,
        size: 40,
        health: 200,
        color: '#dc2626',
        darkColor: '#7f1d1d',
        bulletConfig: { speed: 250, size: 10, damage: 80 },
        shootCooldown: 3500,
        aggroRange: 350,
    },
};
